all:
	gfortran -c -O -fno-align-commons active.f
	gfortran -c -O -fno-align-commons alchemy.f
	gfortran -c -O -fno-align-commons analysis.f
	gfortran -c -O -fno-align-commons analyze_qommma.f
	gfortran -c -O -fno-align-commons angles.f
	gfortran -c -O -fno-align-commons anneal.f
	gfortran -c -O -fno-align-commons archive.f
	gfortran -c -O -fno-align-commons attach.f
	gfortran -c -O -fno-align-commons basefile.f
	gfortran -c -O -fno-align-commons beeman.f
	gfortran -c -O -fno-align-commons bicubic.f
	gfortran -c -O -fno-align-commons bitors.f
	gfortran -c -O -fno-align-commons bonds.f
	gfortran -c -O -fno-align-commons born.f
	gfortran -c -O -fno-align-commons bounds.f
	gfortran -c -O -fno-align-commons bussi.f
	gfortran -c -O -fno-align-commons calendar.f
	gfortran -c -O -fno-align-commons center.f
	gfortran -c -O -fno-align-commons chkpole.f
	gfortran -c -O -fno-align-commons chkring.f
	gfortran -c -O -fno-align-commons chkxyz.f
	gfortran -c -O -fno-align-commons cholesky.f
	gfortran -c -O -fno-align-commons clock.f
	gfortran -c -O -fno-align-commons cluster.f
	gfortran -c -O -fno-align-commons column.f
	gfortran -c -O -fno-align-commons command.f
	gfortran -c -O -fno-align-commons connect.f
	gfortran -c -O -fno-align-commons connolly.f
	gfortran -c -O -fno-align-commons control.f
	gfortran -c -O -fno-align-commons correlate.f
	gfortran -c -O -fno-align-commons crystal.f
	gfortran -c -O -fno-align-commons cspline.f
	gfortran -c -O -fno-align-commons cutoffs.f
	gfortran -c -O -fno-align-commons deflate.f
	gfortran -c -O -fno-align-commons delete.f
	gfortran -c -O -fno-align-commons diagq.f
	gfortran -c -O -fno-align-commons diffeq.f
	gfortran -c -O -fno-align-commons diffuse.f
	gfortran -c -O -fno-align-commons distgeom.f
	gfortran -c -O -fno-align-commons document.f
	gfortran -c -O -fno-align-commons dynamic.f
	gfortran -c -O -fno-align-commons eangang.f
	gfortran -c -O -fno-align-commons eangang1.f
	gfortran -c -O -fno-align-commons eangang2.f
	gfortran -c -O -fno-align-commons eangang3.f
	gfortran -c -O -fno-align-commons eangle.f
	gfortran -c -O -fno-align-commons eangle1.f
	gfortran -c -O -fno-align-commons eangle2.f
	gfortran -c -O -fno-align-commons eangle3.f
	gfortran -c -O -fno-align-commons ebond.f
	gfortran -c -O -fno-align-commons ebond1.f
	gfortran -c -O -fno-align-commons ebond2.f
	gfortran -c -O -fno-align-commons ebond3.f
	gfortran -c -O -fno-align-commons ebuck.f
	gfortran -c -O -fno-align-commons ebuck1.f
	gfortran -c -O -fno-align-commons ebuck2.f
	gfortran -c -O -fno-align-commons ebuck3.f
	gfortran -c -O -fno-align-commons echarge.f
	gfortran -c -O -fno-align-commons echarge1.f
	gfortran -c -O -fno-align-commons echarge2.f
	gfortran -c -O -fno-align-commons echarge3.f
	gfortran -c -O -fno-align-commons echgdpl.f
	gfortran -c -O -fno-align-commons echgdpl1.f
	gfortran -c -O -fno-align-commons echgdpl2.f
	gfortran -c -O -fno-align-commons echgdpl3.f
	gfortran -c -O -fno-align-commons edipole.f
	gfortran -c -O -fno-align-commons edipole1.f
	gfortran -c -O -fno-align-commons edipole2.f
	gfortran -c -O -fno-align-commons edipole3.f
	gfortran -c -O -fno-align-commons egauss.f
	gfortran -c -O -fno-align-commons egauss1.f
	gfortran -c -O -fno-align-commons egauss2.f
	gfortran -c -O -fno-align-commons egauss3.f
	gfortran -c -O -fno-align-commons egeom.f
	gfortran -c -O -fno-align-commons egeom1.f
	gfortran -c -O -fno-align-commons egeom2.f
	gfortran -c -O -fno-align-commons egeom3.f
	gfortran -c -O -fno-align-commons ehal.f
	gfortran -c -O -fno-align-commons ehal1.f
	gfortran -c -O -fno-align-commons ehal2.f
	gfortran -c -O -fno-align-commons ehal3.f
	gfortran -c -O -fno-align-commons eimprop.f
	gfortran -c -O -fno-align-commons eimprop1.f
	gfortran -c -O -fno-align-commons eimprop2.f
	gfortran -c -O -fno-align-commons eimprop3.f
	gfortran -c -O -fno-align-commons eimptor.f
	gfortran -c -O -fno-align-commons eimptor1.f
	gfortran -c -O -fno-align-commons eimptor2.f
	gfortran -c -O -fno-align-commons eimptor3.f
	gfortran -c -O -fno-align-commons elj.f
	gfortran -c -O -fno-align-commons elj1.f
	gfortran -c -O -fno-align-commons elj2.f
	gfortran -c -O -fno-align-commons elj3.f
	gfortran -c -O -fno-align-commons embed.f
	gfortran -c -O -fno-align-commons emetal.f
	gfortran -c -O -fno-align-commons emetal1.f
	gfortran -c -O -fno-align-commons emetal2.f
	gfortran -c -O -fno-align-commons emetal3.f
	gfortran -c -O -fno-align-commons emm3hb.f
	gfortran -c -O -fno-align-commons emm3hb1.f
	gfortran -c -O -fno-align-commons emm3hb2.f
	gfortran -c -O -fno-align-commons emm3hb3.f
	gfortran -c -O -fno-align-commons empole.f
	gfortran -c -O -fno-align-commons empole1.f
	gfortran -c -O -fno-align-commons empole2.f
	gfortran -c -O -fno-align-commons empole3.f
	gfortran -c -O -fno-align-commons energy.f
	gfortran -c -O -fno-align-commons eopbend.f
	gfortran -c -O -fno-align-commons eopbend1.f
	gfortran -c -O -fno-align-commons eopbend2.f
	gfortran -c -O -fno-align-commons eopbend3.f
	gfortran -c -O -fno-align-commons eopdist.f
	gfortran -c -O -fno-align-commons eopdist1.f
	gfortran -c -O -fno-align-commons eopdist2.f
	gfortran -c -O -fno-align-commons eopdist3.f
	gfortran -c -O -fno-align-commons epitors.f
	gfortran -c -O -fno-align-commons epitors1.f
	gfortran -c -O -fno-align-commons epitors2.f
	gfortran -c -O -fno-align-commons epitors3.f
	gfortran -c -O -fno-align-commons erf.f
	gfortran -c -O -fno-align-commons erxnfld.f
	gfortran -c -O -fno-align-commons erxnfld1.f
	gfortran -c -O -fno-align-commons erxnfld2.f
	gfortran -c -O -fno-align-commons erxnfld3.f
	gfortran -c -O -fno-align-commons esolv.f
	gfortran -c -O -fno-align-commons esolv1.f
	gfortran -c -O -fno-align-commons esolv2.f
	gfortran -c -O -fno-align-commons esolv3.f
	gfortran -c -O -fno-align-commons estrbnd.f
	gfortran -c -O -fno-align-commons estrbnd1.f
	gfortran -c -O -fno-align-commons estrbnd2.f
	gfortran -c -O -fno-align-commons estrbnd3.f
	gfortran -c -O -fno-align-commons estrtor.f
	gfortran -c -O -fno-align-commons estrtor1.f
	gfortran -c -O -fno-align-commons estrtor2.f
	gfortran -c -O -fno-align-commons estrtor3.f
	gfortran -c -O -fno-align-commons etors.f
	gfortran -c -O -fno-align-commons etors1.f
	gfortran -c -O -fno-align-commons etors2.f
	gfortran -c -O -fno-align-commons etors3.f
	gfortran -c -O -fno-align-commons etortor.f
	gfortran -c -O -fno-align-commons etortor1.f
	gfortran -c -O -fno-align-commons etortor2.f
	gfortran -c -O -fno-align-commons etortor3.f
	gfortran -c -O -fno-align-commons eurey.f
	gfortran -c -O -fno-align-commons eurey1.f
	gfortran -c -O -fno-align-commons eurey2.f
	gfortran -c -O -fno-align-commons eurey3.f
	gfortran -c -O -fno-align-commons evcorr.f
	gfortran -c -O -fno-align-commons extra_qommma.f
	gfortran -c -O -fno-align-commons extra1_qommma.f
	gfortran -c -O -fno-align-commons extra2.f
	gfortran -c -O -fno-align-commons extra3.f
	gfortran -c -O -fno-align-commons fatal.f
	gfortran -c -O -fno-align-commons fft3d.f
	gfortran -c -O -fno-align-commons fftpack.f
	gfortran -c -O -fno-align-commons field.f
	gfortran -c -O -fno-align-commons final.f
	gfortran -c -O -fno-align-commons flatten.f
	gfortran -c -O -fno-align-commons freeunit.f
	gfortran -c -O -fno-align-commons gda.f
	gfortran -c -O -fno-align-commons geometry.f
	gfortran -c -O -fno-align-commons getint.f
	gfortran -c -O -fno-align-commons getkey.f
	gfortran -c -O -fno-align-commons getmol.f
	gfortran -c -O -fno-align-commons getmol2.f
	gfortran -c -O -fno-align-commons getnumb.f
	gfortran -c -O -fno-align-commons getpdb.f
	gfortran -c -O -fno-align-commons getprm.f
	gfortran -c -O -fno-align-commons getref.f
	gfortran -c -O -fno-align-commons getstring.f
	gfortran -c -O -fno-align-commons gettext.f
	gfortran -c -O -fno-align-commons getword.f
	gfortran -c -O -fno-align-commons getxyz.f
	gfortran -c -O -fno-align-commons ghmcstep.f
	gfortran -c -O -fno-align-commons gradient.f
	gfortran -c -O -fno-align-commons gradrgd.f
	gfortran -c -O -fno-align-commons gradrot.f
	gfortran -c -O -fno-align-commons groups.f
	gfortran -c -O -fno-align-commons grpline.f
	gfortran -c -O -fno-align-commons gyrate.f
	gfortran -c -O -fno-align-commons hessian.f
	gfortran -c -O -fno-align-commons hessrgd.f
	gfortran -c -O -fno-align-commons hessrot.f
	gfortran -c -O -fno-align-commons hybrid.f
	gfortran -c -O -fno-align-commons image.f
	gfortran -c -O -fno-align-commons impose.f
	gfortran -c -O -fno-align-commons induce.f
	gfortran -c -O -fno-align-commons inertia.f
	gfortran -c -O -fno-align-commons initatom.f
	gfortran -c -O -fno-align-commons initial.f
	gfortran -c -O -fno-align-commons initprm.f
	gfortran -c -O -fno-align-commons initres.f
	gfortran -c -O -fno-align-commons initrot.f
	gfortran -c -O -fno-align-commons insert.f
	gfortran -c -O -fno-align-commons intedit.f
	gfortran -c -O -fno-align-commons intxyz.f
	gfortran -c -O -fno-align-commons invbeta.f
	gfortran -c -O -fno-align-commons invert.f
	gfortran -c -O -fno-align-commons jacobi.f
	gfortran -c -O -fno-align-commons kangang.f
	gfortran -c -O -fno-align-commons kangle.f
	gfortran -c -O -fno-align-commons katom.f
	gfortran -c -O -fno-align-commons kbond.f
	gfortran -c -O -fno-align-commons kcharge.f
	gfortran -c -O -fno-align-commons kdipole.f
	gfortran -c -O -fno-align-commons kewald.f
	gfortran -c -O -fno-align-commons kgeom.f
	gfortran -c -O -fno-align-commons kimprop.f
	gfortran -c -O -fno-align-commons kimptor.f
	gfortran -c -O -fno-align-commons kinetic.f
	gfortran -c -O -fno-align-commons kmetal.f
	gfortran -c -O -fno-align-commons kmpole.f
	gfortran -c -O -fno-align-commons kopbend.f
	gfortran -c -O -fno-align-commons kopdist.f
	gfortran -c -O -fno-align-commons korbit.f
	gfortran -c -O -fno-align-commons kpitors.f
	gfortran -c -O -fno-align-commons kpolar.f
	gfortran -c -O -fno-align-commons ksolv.f
	gfortran -c -O -fno-align-commons kstrbnd.f
	gfortran -c -O -fno-align-commons kstrtor.f
	gfortran -c -O -fno-align-commons ktors.f
	gfortran -c -O -fno-align-commons ktortor.f
	gfortran -c -O -fno-align-commons kurey.f
	gfortran -c -O -fno-align-commons kvdw.f
	gfortran -c -O -fno-align-commons lattice.f
	gfortran -c -O -fno-align-commons lbfgs.f
	gfortran -c -O -fno-align-commons lights.f
	gfortran -c -O -fno-align-commons makeint.f
	gfortran -c -O -fno-align-commons makeref.f
	gfortran -c -O -fno-align-commons makexyz.f
	gfortran -c -O -fno-align-commons maxwell.f
	gfortran -c -O -fno-align-commons mdinit.f
	gfortran -c -O -fno-align-commons mdrest.f
	gfortran -c -O -fno-align-commons mdsave.f
	gfortran -c -O -fno-align-commons mdstat.f
	gfortran -c -O -fno-align-commons mechanic.f
	gfortran -c -O -fno-align-commons merge.f
	gfortran -c -O -fno-align-commons minimize.f
	gfortran -c -O -fno-align-commons minirot.f
	gfortran -c -O -fno-align-commons minrigid.f
	gfortran -c -O -fno-align-commons molecule.f
	gfortran -c -O -fno-align-commons molxyz.f
	gfortran -c -O -fno-align-commons moments.f
	gfortran -c -O -fno-align-commons monte.f
	gfortran -c -O -fno-align-commons mutate.f
	gfortran -c -O -fno-align-commons nblist.f
	gfortran -c -O -fno-align-commons newton.f
	gfortran -c -O -fno-align-commons newtrot.f
	gfortran -c -O -fno-align-commons nextarg.f
	gfortran -c -O -fno-align-commons nexttext.f
	gfortran -c -O -fno-align-commons nose.f
	gfortran -c -O -fno-align-commons nspline.f
	gfortran -c -O -fno-align-commons nucleic.f
	gfortran -c -O -fno-align-commons number.f
	gfortran -c -O -fno-align-commons numeral.f
	gfortran -c -O -fno-align-commons numgrad.f
	gfortran -c -O -fno-align-commons ocvm.f
	gfortran -c -O -fno-align-commons openend.f
	gfortran -c -O -fno-align-commons optimize.f
	gfortran -c -O -fno-align-commons optirot.f
	gfortran -c -O -fno-align-commons optrigid.f
	gfortran -c -O -fno-align-commons optsave.f
	gfortran -c -O -fno-align-commons orbital.f
	gfortran -c -O -fno-align-commons orient.f
	gfortran -c -O -fno-align-commons orthog.f
	gfortran -c -O -fno-align-commons overlap.f
	gfortran -c -O -fno-align-commons path.f
	gfortran -c -O -fno-align-commons pdbxyz.f
	gfortran -c -O -fno-align-commons picalc.f
	gfortran -c -O -fno-align-commons pmestuff.f
	gfortran -c -O -fno-align-commons pmpb.f
	gfortran -c -O -fno-align-commons polarize.f
	gfortran -c -O -fno-align-commons poledit.f
	gfortran -c -O -fno-align-commons polymer.f
	gfortran -c -O -fno-align-commons potential.f
	gfortran -c -O -fno-align-commons precise.f
	gfortran -c -O -fno-align-commons pressure.f
	gfortran -c -O -fno-align-commons prmedit.f
	gfortran -c -O -fno-align-commons prmkey_qommma.f
	gfortran -c -O -fno-align-commons promo.f
	gfortran -c -O -fno-align-commons protein.f
	gfortran -c -O -fno-align-commons prtdyn.f
	gfortran -c -O -fno-align-commons prterr.f
	gfortran -c -O -fno-align-commons prtint.f
	gfortran -c -O -fno-align-commons prtmol2.f
	gfortran -c -O -fno-align-commons prtpdb.f
	gfortran -c -O -fno-align-commons prtprm.f
	gfortran -c -O -fno-align-commons prtseq.f
	gfortran -c -O -fno-align-commons prtxyz.f
	gfortran -c -O -fno-align-commons pss.f
	gfortran -c -O -fno-align-commons pssrigid.f
	gfortran -c -O -fno-align-commons pssrot.f
	gfortran -c -O -fno-align-commons quatfit.f
	gfortran -c -O -fno-align-commons radial.f
	gfortran -c -O -fno-align-commons random.f
	gfortran -c -O -fno-align-commons rattle.f
	gfortran -c -O -fno-align-commons readdyn.f
	gfortran -c -O -fno-align-commons readgau.f
	gfortran -c -O -fno-align-commons readint.f
	gfortran -c -O -fno-align-commons readmol.f
	gfortran -c -O -fno-align-commons readmol2.f
	gfortran -c -O -fno-align-commons readpdb.f
	gfortran -c -O -fno-align-commons readprm.f
	gfortran -c -O -fno-align-commons readseq.f
	gfortran -c -O -fno-align-commons readxyz.f
	gfortran -c -O -fno-align-commons replica.f
	gfortran -c -O -fno-align-commons respa.f
	gfortran -c -O -fno-align-commons rgdstep.f
	gfortran -c -O -fno-align-commons rings.f
	gfortran -c -O -fno-align-commons rmsfit.f
	gfortran -c -O -fno-align-commons rotlist.f
	gfortran -c -O -fno-align-commons rotpole.f
	gfortran -c -O -fno-align-commons saddle.f
	gfortran -c -O -fno-align-commons scan.f
	gfortran -c -O -fno-align-commons sdstep.f
	gfortran -c -O -fno-align-commons search.f
	gfortran -c -O -fno-align-commons server.f
	gfortran -c -O -fno-align-commons shakeup.f
	gfortran -c -O -fno-align-commons sigmoid.f
	gfortran -c -O -fno-align-commons sktstuff.f
	gfortran -c -O -fno-align-commons sniffer.f
	gfortran -c -O -fno-align-commons sort.f
	gfortran -c -O -fno-align-commons spacefill.f
	gfortran -c -O -fno-align-commons spectrum.f
	gfortran -c -O -fno-align-commons square.f
	gfortran -c -O -fno-align-commons suffix.f
	gfortran -c -O -fno-align-commons superpose.f
	gfortran -c -O -fno-align-commons surface.f
	gfortran -c -O -fno-align-commons surfatom.f
	gfortran -c -O -fno-align-commons switch.f
	gfortran -c -O -fno-align-commons sybylxyz.f
	gfortran -c -O -fno-align-commons temper.f
	gfortran -c -O -fno-align-commons testgrad.f
	gfortran -c -O -fno-align-commons testhess.f
	gfortran -c -O -fno-align-commons testpair.f
	gfortran -c -O -fno-align-commons testrot.f
	gfortran -c -O -fno-align-commons timer.f
	gfortran -c -O -fno-align-commons timerot.f
	gfortran -c -O -fno-align-commons tncg.f
	gfortran -c -O -fno-align-commons torphase.f
	gfortran -c -O -fno-align-commons torque.f
	gfortran -c -O -fno-align-commons torsfit.f
	gfortran -c -O -fno-align-commons torsions.f
	gfortran -c -O -fno-align-commons trimtext.f
	gfortran -c -O -fno-align-commons unitcell.f
	gfortran -c -O -fno-align-commons valence.f
	gfortran -c -O -fno-align-commons verlet.f
	gfortran -c -O -fno-align-commons version.f
	gfortran -c -O -fno-align-commons vibbig.f
	gfortran -c -O -fno-align-commons vibrate.f
	gfortran -c -O -fno-align-commons vibrot.f
	gfortran -c -O -fno-align-commons volume.f
	gfortran -c -O -fno-align-commons xtalfit.f
	gfortran -c -O -fno-align-commons xtalmin.f
	gfortran -c -O -fno-align-commons xyzatm.f
	gfortran -c -O -fno-align-commons xyzedit.f
	gfortran -c -O -fno-align-commons xyzint.f
	gfortran -c -O -fno-align-commons xyzpdb.f
	gfortran -c -O -fno-align-commons xyzsybyl.f
	gfortran -c -O -fno-align-commons zatom.f
	gfortran -c -O -fno-align-commons readdiffgrad_qommma.f
	ar -crusv libtinker.a \
	active.o \
	analysis.o \
	angles.o \
	attach.o \
	basefile.o \
	beeman.o \
	bicubic.o \
	bitors.o \
	bonds.o \
	born.o \
	bounds.o \
	bussi.o \
	calendar.o \
	center.o \
	chkpole.o \
	chkring.o \
	chkxyz.o \
	cholesky.o \
	clock.o \
	cluster.o \
	column.o \
	command.o \
	connect.o \
	connolly.o \
	control.o \
	cspline.o \
	cutoffs.o \
	deflate.o \
	delete.o \
	diagq.o \
	diffeq.o \
	eangang.o \
	eangang1.o \
	eangang2.o \
	eangang3.o \
	eangle.o \
	eangle1.o \
	eangle2.o \
	eangle3.o \
	ebond.o \
	ebond1.o \
	ebond2.o \
	ebond3.o \
	ebuck.o \
	ebuck1.o \
	ebuck2.o \
	ebuck3.o \
	echarge.o \
	echarge1.o \
	echarge2.o \
	echarge3.o \
	echgdpl.o \
	echgdpl1.o \
	echgdpl2.o \
	echgdpl3.o \
	edipole.o \
	edipole1.o \
	edipole2.o \
	edipole3.o \
	egauss.o \
	egauss1.o \
	egauss2.o \
	egauss3.o \
	egeom.o \
	egeom1.o \
	egeom2.o \
	egeom3.o \
	ehal.o \
	ehal1.o \
	ehal2.o \
	ehal3.o \
	eimprop.o \
	eimprop1.o \
	eimprop2.o \
	eimprop3.o \
	eimptor.o \
	eimptor1.o \
	eimptor2.o \
	eimptor3.o \
	elj.o \
	elj1.o \
	elj2.o \
	elj3.o \
	embed.o \
	emetal.o \
	emetal1.o \
	emetal2.o \
	emetal3.o \
	emm3hb.o \
	emm3hb1.o \
	emm3hb2.o \
	emm3hb3.o \
	empole.o \
	empole1.o \
	empole2.o \
	empole3.o \
	energy.o \
	eopbend.o \
	eopbend1.o \
	eopbend2.o \
	eopbend3.o \
	eopdist.o \
	eopdist1.o \
	eopdist2.o \
	eopdist3.o \
	epitors.o \
	epitors1.o \
	epitors2.o \
	epitors3.o \
	erf.o \
	erxnfld.o \
	erxnfld1.o \
	erxnfld2.o \
	erxnfld3.o \
	esolv.o \
	esolv1.o \
	esolv2.o \
	esolv3.o \
	estrbnd.o \
	estrbnd1.o \
	estrbnd2.o \
	estrbnd3.o \
	estrtor.o \
	estrtor1.o \
	estrtor2.o \
	estrtor3.o \
	etors.o \
	etors1.o \
	etors2.o \
	etors3.o \
	etortor.o \
	etortor1.o \
	etortor2.o \
	etortor3.o \
	eurey.o \
	eurey1.o \
	eurey2.o \
	eurey3.o \
	evcorr.o \
	extra_qommma.o \
	extra1_qommma.o \
	extra2.o \
	extra3.o \
	fatal.o \
	fft3d.o \
	fftpack.o \
	field.o \
	final.o \
	flatten.o \
	freeunit.o \
	geometry.o \
	getint.o \
	getkey.o \
	getmol.o \
	getmol2.o \
	getnumb.o \
	getpdb.o \
	getprm.o \
	getref.o \
	getstring.o \
	gettext.o \
	getword.o \
	getxyz.o \
	ghmcstep.o \
	gradient.o \
	gradrgd.o \
	gradrot.o \
	groups.o \
	grpline.o \
	gyrate.o \
	hessian.o \
	hessrgd.o \
	hessrot.o \
	hybrid.o \
	image.o \
	impose.o \
	induce.o \
	inertia.o \
	initatom.o \
	initial.o \
	initprm.o \
	initres.o \
	initrot.o \
	insert.o \
	invbeta.o \
	invert.o \
	jacobi.o \
	kangang.o \
	kangle.o \
	katom.o \
	kbond.o \
	kcharge.o \
	kdipole.o \
	kewald.o \
	kgeom.o \
	kimprop.o \
	kimptor.o \
	kinetic.o \
	kmetal.o \
	kmpole.o \
	kopbend.o \
	kopdist.o \
	korbit.o \
	kpitors.o \
	kpolar.o \
	ksolv.o \
	kstrbnd.o \
	kstrtor.o \
	ktors.o \
	ktortor.o \
	kurey.o \
	kvdw.o \
	lattice.o \
	lbfgs.o \
	lights.o \
	makeint.o \
	makeref.o \
	makexyz.o \
	maxwell.o \
	mdinit.o \
	mdrest.o \
	mdsave.o \
	mdstat.o \
	mechanic.o \
	merge.o \
	molecule.o \
	moments.o \
	mutate.o \
	nblist.o \
	nextarg.o \
	nexttext.o \
	nose.o \
	nspline.o \
	number.o \
	numeral.o \
	numgrad.o \
	ocvm.o \
	openend.o \
	optsave.o \
	orbital.o \
	orient.o \
	orthog.o \
	overlap.o \
	picalc.o \
	pmestuff.o \
	pmpb.o \
	polymer.o \
	precise.o \
	pressure.o \
	prmkey_qommma.o \
	promo.o \
	prtdyn.o \
	prterr.o \
	prtint.o \
	prtmol2.o \
	prtpdb.o \
	prtprm.o \
	prtseq.o \
	prtxyz.o \
	quatfit.o \
	random.o \
	rattle.o \
	readdiffgrad_qommma.o \
	readdyn.o \
	readgau.o \
	readint.o \
	readmol.o \
	readmol2.o \
	readpdb.o \
	readprm.o \
	readseq.o \
	readxyz.o \
	replica.o \
	respa.o \
	rgdstep.o \
	rings.o \
	rmsfit.o \
	rotlist.o \
	rotpole.o \
	sdstep.o \
	search.o \
	server.o \
	shakeup.o \
	sigmoid.o \
	sktstuff.o \
	sort.o \
	square.o \
	suffix.o \
	surface.o \
	surfatom.o \
	switch.o \
	temper.o \
	tncg.o \
	torphase.o \
	torque.o \
	torsions.o \
	trimtext.o \
	unitcell.o \
	verlet.o \
	version.o \
	volume.o \
	xyzatm.o \
	zatom.o
	gfortran  -s -o analyze_qommma.x analyze_qommma.o libtinker.a
	gfortran  -s -o minimize_qommma.x minimize.o libtinker.a
