	gfortran-6 -c -O -fno-align-commons active.f
	gfortran-6 -c -O -fno-align-commons alchemy.f
	gfortran-6 -c -O -fno-align-commons analysis.f
	gfortran-6 -c -O -fno-align-commons analyze_qommma.f
	gfortran-6 -c -O -fno-align-commons angles.f
	gfortran-6 -c -O -fno-align-commons anneal.f
	gfortran-6 -c -O -fno-align-commons archive.f
	gfortran-6 -c -O -fno-align-commons attach.f
	gfortran-6 -c -O -fno-align-commons basefile.f
	gfortran-6 -c -O -fno-align-commons beeman.f
	gfortran-6 -c -O -fno-align-commons bicubic.f
	gfortran-6 -c -O -fno-align-commons bitors.f
	gfortran-6 -c -O -fno-align-commons bonds.f
	gfortran-6 -c -O -fno-align-commons born.f
	gfortran-6 -c -O -fno-align-commons bounds.f
	gfortran-6 -c -O -fno-align-commons bussi.f
	gfortran-6 -c -O -fno-align-commons calendar.f
	gfortran-6 -c -O -fno-align-commons center.f
	gfortran-6 -c -O -fno-align-commons chkpole.f
	gfortran-6 -c -O -fno-align-commons chkring.f
	gfortran-6 -c -O -fno-align-commons chkxyz.f
	gfortran-6 -c -O -fno-align-commons cholesky.f
	gfortran-6 -c -O -fno-align-commons clock.f
	gfortran-6 -c -O -fno-align-commons cluster.f
	gfortran-6 -c -O -fno-align-commons column.f
	gfortran-6 -c -O -fno-align-commons command.f
	gfortran-6 -c -O -fno-align-commons connect.f
	gfortran-6 -c -O -fno-align-commons connolly.f
	gfortran-6 -c -O -fno-align-commons control.f
	gfortran-6 -c -O -fno-align-commons correlate.f
	gfortran-6 -c -O -fno-align-commons crystal.f
	gfortran-6 -c -O -fno-align-commons cspline.f
	gfortran-6 -c -O -fno-align-commons cutoffs.f
	gfortran-6 -c -O -fno-align-commons deflate.f
	gfortran-6 -c -O -fno-align-commons delete.f
	gfortran-6 -c -O -fno-align-commons diagq.f
	gfortran-6 -c -O -fno-align-commons diffeq.f
	gfortran-6 -c -O -fno-align-commons diffuse.f
	gfortran-6 -c -O -fno-align-commons distgeom.f
	gfortran-6 -c -O -fno-align-commons document.f
	gfortran-6 -c -O -fno-align-commons dynamic.f
	gfortran-6 -c -O -fno-align-commons eangang.f
	gfortran-6 -c -O -fno-align-commons eangang1.f
	gfortran-6 -c -O -fno-align-commons eangang2.f
	gfortran-6 -c -O -fno-align-commons eangang3.f
	gfortran-6 -c -O -fno-align-commons eangle.f
	gfortran-6 -c -O -fno-align-commons eangle1.f
	gfortran-6 -c -O -fno-align-commons eangle2.f
	gfortran-6 -c -O -fno-align-commons eangle3.f
	gfortran-6 -c -O -fno-align-commons ebond.f
	gfortran-6 -c -O -fno-align-commons ebond1.f
	gfortran-6 -c -O -fno-align-commons ebond2.f
	gfortran-6 -c -O -fno-align-commons ebond3.f
	gfortran-6 -c -O -fno-align-commons ebuck.f
	gfortran-6 -c -O -fno-align-commons ebuck1.f
	gfortran-6 -c -O -fno-align-commons ebuck2.f
	gfortran-6 -c -O -fno-align-commons ebuck3.f
	gfortran-6 -c -O -fno-align-commons echarge.f
	gfortran-6 -c -O -fno-align-commons echarge1.f
	gfortran-6 -c -O -fno-align-commons echarge2.f
	gfortran-6 -c -O -fno-align-commons echarge3.f
	gfortran-6 -c -O -fno-align-commons echgdpl.f
	gfortran-6 -c -O -fno-align-commons echgdpl1.f
	gfortran-6 -c -O -fno-align-commons echgdpl2.f
	gfortran-6 -c -O -fno-align-commons echgdpl3.f
	gfortran-6 -c -O -fno-align-commons edipole.f
	gfortran-6 -c -O -fno-align-commons edipole1.f
	gfortran-6 -c -O -fno-align-commons edipole2.f
	gfortran-6 -c -O -fno-align-commons edipole3.f
	gfortran-6 -c -O -fno-align-commons egauss.f
	gfortran-6 -c -O -fno-align-commons egauss1.f
	gfortran-6 -c -O -fno-align-commons egauss2.f
	gfortran-6 -c -O -fno-align-commons egauss3.f
	gfortran-6 -c -O -fno-align-commons egeom.f
	gfortran-6 -c -O -fno-align-commons egeom1.f
	gfortran-6 -c -O -fno-align-commons egeom2.f
	gfortran-6 -c -O -fno-align-commons egeom3.f
	gfortran-6 -c -O -fno-align-commons ehal.f
	gfortran-6 -c -O -fno-align-commons ehal1.f
	gfortran-6 -c -O -fno-align-commons ehal2.f
	gfortran-6 -c -O -fno-align-commons ehal3.f
	gfortran-6 -c -O -fno-align-commons eimprop.f
	gfortran-6 -c -O -fno-align-commons eimprop1.f
	gfortran-6 -c -O -fno-align-commons eimprop2.f
	gfortran-6 -c -O -fno-align-commons eimprop3.f
	gfortran-6 -c -O -fno-align-commons eimptor.f
	gfortran-6 -c -O -fno-align-commons eimptor1.f
	gfortran-6 -c -O -fno-align-commons eimptor2.f
	gfortran-6 -c -O -fno-align-commons eimptor3.f
	gfortran-6 -c -O -fno-align-commons elj.f
	gfortran-6 -c -O -fno-align-commons elj1.f
	gfortran-6 -c -O -fno-align-commons elj2.f
	gfortran-6 -c -O -fno-align-commons elj3.f
	gfortran-6 -c -O -fno-align-commons embed.f
	gfortran-6 -c -O -fno-align-commons emetal.f
	gfortran-6 -c -O -fno-align-commons emetal1.f
	gfortran-6 -c -O -fno-align-commons emetal2.f
	gfortran-6 -c -O -fno-align-commons emetal3.f
	gfortran-6 -c -O -fno-align-commons emm3hb.f
	gfortran-6 -c -O -fno-align-commons emm3hb1.f
	gfortran-6 -c -O -fno-align-commons emm3hb2.f
	gfortran-6 -c -O -fno-align-commons emm3hb3.f
	gfortran-6 -c -O -fno-align-commons empole.f
	gfortran-6 -c -O -fno-align-commons empole1.f
	gfortran-6 -c -O -fno-align-commons empole2.f
	gfortran-6 -c -O -fno-align-commons empole3.f
	gfortran-6 -c -O -fno-align-commons energy.f
	gfortran-6 -c -O -fno-align-commons eopbend.f
	gfortran-6 -c -O -fno-align-commons eopbend1.f
	gfortran-6 -c -O -fno-align-commons eopbend2.f
	gfortran-6 -c -O -fno-align-commons eopbend3.f
	gfortran-6 -c -O -fno-align-commons eopdist.f
	gfortran-6 -c -O -fno-align-commons eopdist1.f
	gfortran-6 -c -O -fno-align-commons eopdist2.f
	gfortran-6 -c -O -fno-align-commons eopdist3.f
	gfortran-6 -c -O -fno-align-commons epitors.f
	gfortran-6 -c -O -fno-align-commons epitors1.f
	gfortran-6 -c -O -fno-align-commons epitors2.f
	gfortran-6 -c -O -fno-align-commons epitors3.f
	gfortran-6 -c -O -fno-align-commons erf.f
	gfortran-6 -c -O -fno-align-commons erxnfld.f
	gfortran-6 -c -O -fno-align-commons erxnfld1.f
	gfortran-6 -c -O -fno-align-commons erxnfld2.f
	gfortran-6 -c -O -fno-align-commons erxnfld3.f
	gfortran-6 -c -O -fno-align-commons esolv.f
	gfortran-6 -c -O -fno-align-commons esolv1.f
	gfortran-6 -c -O -fno-align-commons esolv2.f
	gfortran-6 -c -O -fno-align-commons esolv3.f
	gfortran-6 -c -O -fno-align-commons estrbnd.f
	gfortran-6 -c -O -fno-align-commons estrbnd1.f
	gfortran-6 -c -O -fno-align-commons estrbnd2.f
	gfortran-6 -c -O -fno-align-commons estrbnd3.f
	gfortran-6 -c -O -fno-align-commons estrtor.f
	gfortran-6 -c -O -fno-align-commons estrtor1.f
	gfortran-6 -c -O -fno-align-commons estrtor2.f
	gfortran-6 -c -O -fno-align-commons estrtor3.f
	gfortran-6 -c -O -fno-align-commons etors.f
	gfortran-6 -c -O -fno-align-commons etors1.f
	gfortran-6 -c -O -fno-align-commons etors2.f
	gfortran-6 -c -O -fno-align-commons etors3.f
	gfortran-6 -c -O -fno-align-commons etortor.f
	gfortran-6 -c -O -fno-align-commons etortor1.f
	gfortran-6 -c -O -fno-align-commons etortor2.f
	gfortran-6 -c -O -fno-align-commons etortor3.f
	gfortran-6 -c -O -fno-align-commons eurey.f
	gfortran-6 -c -O -fno-align-commons eurey1.f
	gfortran-6 -c -O -fno-align-commons eurey2.f
	gfortran-6 -c -O -fno-align-commons eurey3.f
	gfortran-6 -c -O -fno-align-commons evcorr.f
	# pgf90  -c -fast  extra.f
	gfortran-6 -c -O -fno-align-commons extra_qommma.f
	# pgf90  -c -O -fno-align-commons-fast  extra1.f
	gfortran-6 -c -O -fno-align-commons extra1_qommma.f
	gfortran-6 -c -O -fno-align-commons extra2.f
	gfortran-6 -c -O -fno-align-commons extra3.f
	gfortran-6 -c -O -fno-align-commons fatal.f
	gfortran-6 -c -O -fno-align-commons fft3d.f
	gfortran-6 -c -O -fno-align-commons fftpack.f
	gfortran-6 -c -O -fno-align-commons field.f
	gfortran-6 -c -O -fno-align-commons final.f
	gfortran-6 -c -O -fno-align-commons flatten.f
	gfortran-6 -c -O -fno-align-commons freeunit.f
	gfortran-6 -c -O -fno-align-commons gda.f
	gfortran-6 -c -O -fno-align-commons geometry.f
	gfortran-6 -c -O -fno-align-commons getint.f
	gfortran-6 -c -O -fno-align-commons getkey.f
	gfortran-6 -c -O -fno-align-commons getmol.f
	gfortran-6 -c -O -fno-align-commons getmol2.f
	gfortran-6 -c -O -fno-align-commons getnumb.f
	gfortran-6 -c -O -fno-align-commons getpdb.f
	gfortran-6 -c -O -fno-align-commons getprm.f
	gfortran-6 -c -O -fno-align-commons getref.f
	gfortran-6 -c -O -fno-align-commons getstring.f
	gfortran-6 -c -O -fno-align-commons gettext.f
	gfortran-6 -c -O -fno-align-commons getword.f
	gfortran-6 -c -O -fno-align-commons getxyz.f
	gfortran-6 -c -O -fno-align-commons ghmcstep.f
	gfortran-6 -c -O -fno-align-commons gradient.f
	gfortran-6 -c -O -fno-align-commons gradrgd.f
	gfortran-6 -c -O -fno-align-commons gradrot.f
	gfortran-6 -c -O -fno-align-commons groups.f
	gfortran-6 -c -O -fno-align-commons grpline.f
	gfortran-6 -c -O -fno-align-commons gyrate.f
	gfortran-6 -c -O -fno-align-commons hessian.f
	gfortran-6 -c -O -fno-align-commons hessrgd.f
	gfortran-6 -c -O -fno-align-commons hessrot.f
	gfortran-6 -c -O -fno-align-commons hybrid.f
	gfortran-6 -c -O -fno-align-commons image.f
	gfortran-6 -c -O -fno-align-commons impose.f
	gfortran-6 -c -O -fno-align-commons induce.f
	gfortran-6 -c -O -fno-align-commons inertia.f
	gfortran-6 -c -O -fno-align-commons initatom.f
	gfortran-6 -c -O -fno-align-commons initial.f
	gfortran-6 -c -O -fno-align-commons initprm.f
	gfortran-6 -c -O -fno-align-commons initres.f
	gfortran-6 -c -O -fno-align-commons initrot.f
	gfortran-6 -c -O -fno-align-commons insert.f
	gfortran-6 -c -O -fno-align-commons intedit.f
	gfortran-6 -c -O -fno-align-commons intxyz.f
	gfortran-6 -c -O -fno-align-commons invbeta.f
	gfortran-6 -c -O -fno-align-commons invert.f
	gfortran-6 -c -O -fno-align-commons jacobi.f
	gfortran-6 -c -O -fno-align-commons kangang.f
	gfortran-6 -c -O -fno-align-commons kangle.f
	gfortran-6 -c -O -fno-align-commons katom.f
	gfortran-6 -c -O -fno-align-commons kbond.f
	gfortran-6 -c -O -fno-align-commons kcharge.f
	gfortran-6 -c -O -fno-align-commons kdipole.f
	gfortran-6 -c -O -fno-align-commons kewald.f
	gfortran-6 -c -O -fno-align-commons kgeom.f
	gfortran-6 -c -O -fno-align-commons kimprop.f
	gfortran-6 -c -O -fno-align-commons kimptor.f
	gfortran-6 -c -O -fno-align-commons kinetic.f
	gfortran-6 -c -O -fno-align-commons kmetal.f
	gfortran-6 -c -O -fno-align-commons kmpole.f
	gfortran-6 -c -O -fno-align-commons kopbend.f
	gfortran-6 -c -O -fno-align-commons kopdist.f
	gfortran-6 -c -O -fno-align-commons korbit.f
	gfortran-6 -c -O -fno-align-commons kpitors.f
	gfortran-6 -c -O -fno-align-commons kpolar.f
	gfortran-6 -c -O -fno-align-commons ksolv.f
	gfortran-6 -c -O -fno-align-commons kstrbnd.f
	gfortran-6 -c -O -fno-align-commons kstrtor.f
	gfortran-6 -c -O -fno-align-commons ktors.f
	gfortran-6 -c -O -fno-align-commons ktortor.f
	gfortran-6 -c -O -fno-align-commons kurey.f
	gfortran-6 -c -O -fno-align-commons kvdw.f
	gfortran-6 -c -O -fno-align-commons lattice.f
	gfortran-6 -c -O -fno-align-commons lbfgs.f
	gfortran-6 -c -O -fno-align-commons lights.f
	gfortran-6 -c -O -fno-align-commons makeint.f
	gfortran-6 -c -O -fno-align-commons makeref.f
	gfortran-6 -c -O -fno-align-commons makexyz.f
	gfortran-6 -c -O -fno-align-commons maxwell.f
	gfortran-6 -c -O -fno-align-commons mdinit.f
	gfortran-6 -c -O -fno-align-commons mdrest.f
	gfortran-6 -c -O -fno-align-commons mdsave.f
	gfortran-6 -c -O -fno-align-commons mdstat.f
	gfortran-6 -c -O -fno-align-commons mechanic.f
	gfortran-6 -c -O -fno-align-commons merge.f
	gfortran-6 -c -O -fno-align-commons minimize.f
	gfortran-6 -c -O -fno-align-commons minirot.f
	gfortran-6 -c -O -fno-align-commons minrigid.f
	gfortran-6 -c -O -fno-align-commons molecule.f
	gfortran-6 -c -O -fno-align-commons molxyz.f
	gfortran-6 -c -O -fno-align-commons moments.f
	gfortran-6 -c -O -fno-align-commons monte.f
	gfortran-6 -c -O -fno-align-commons mutate.f
	gfortran-6 -c -O -fno-align-commons nblist.f
	gfortran-6 -c -O -fno-align-commons newton.f
	gfortran-6 -c -O -fno-align-commons newtrot.f
	gfortran-6 -c -O -fno-align-commons nextarg.f
	gfortran-6 -c -O -fno-align-commons nexttext.f
	gfortran-6 -c -O -fno-align-commons nose.f
	gfortran-6 -c -O -fno-align-commons nspline.f
	gfortran-6 -c -O -fno-align-commons nucleic.f
	gfortran-6 -c -O -fno-align-commons number.f
	gfortran-6 -c -O -fno-align-commons numeral.f
	gfortran-6 -c -O -fno-align-commons numgrad.f
	gfortran-6 -c -O -fno-align-commons ocvm.f
	gfortran-6 -c -O -fno-align-commons openend.f
	gfortran-6 -c -O -fno-align-commons optimize.f
	gfortran-6 -c -O -fno-align-commons optirot.f
	gfortran-6 -c -O -fno-align-commons optrigid.f
	gfortran-6 -c -O -fno-align-commons optsave.f
	gfortran-6 -c -O -fno-align-commons orbital.f
	gfortran-6 -c -O -fno-align-commons orient.f
	gfortran-6 -c -O -fno-align-commons orthog.f
	gfortran-6 -c -O -fno-align-commons overlap.f
	gfortran-6 -c -O -fno-align-commons path.f
	gfortran-6 -c -O -fno-align-commons pdbxyz.f
	gfortran-6 -c -O -fno-align-commons picalc.f
	gfortran-6 -c -O -fno-align-commons pmestuff.f
	gfortran-6 -c -O -fno-align-commons pmpb.f
	gfortran-6 -c -O -fno-align-commons polarize.f
	gfortran-6 -c -O -fno-align-commons poledit.f
	gfortran-6 -c -O -fno-align-commons polymer.f
	gfortran-6 -c -O -fno-align-commons potential.f
	gfortran-6 -c -O -fno-align-commons precise.f
	gfortran-6 -c -O -fno-align-commons pressure.f
	gfortran-6 -c -O -fno-align-commons prmedit.f
	# pgf90  -c -fast  prmkey.f
	gfortran-6 -c -O -fno-align-commons prmkey_qommma.f
	gfortran-6 -c -O -fno-align-commons promo.f
	gfortran-6 -c -O -fno-align-commons protein.f
	gfortran-6 -c -O -fno-align-commons prtdyn.f
	gfortran-6 -c -O -fno-align-commons prterr.f
	gfortran-6 -c -O -fno-align-commons prtint.f
	gfortran-6 -c -O -fno-align-commons prtmol2.f
	gfortran-6 -c -O -fno-align-commons prtpdb.f
	gfortran-6 -c -O -fno-align-commons prtprm.f
	gfortran-6 -c -O -fno-align-commons prtseq.f
	gfortran-6 -c -O -fno-align-commons prtxyz.f
	gfortran-6 -c -O -fno-align-commons pss.f
	gfortran-6 -c -O -fno-align-commons pssrigid.f
	gfortran-6 -c -O -fno-align-commons pssrot.f
	gfortran-6 -c -O -fno-align-commons quatfit.f
	gfortran-6 -c -O -fno-align-commons radial.f
	gfortran-6 -c -O -fno-align-commons random.f
	gfortran-6 -c -O -fno-align-commons rattle.f
	gfortran-6 -c -O -fno-align-commons readdyn.f
	gfortran-6 -c -O -fno-align-commons readgau.f
	gfortran-6 -c -O -fno-align-commons readint.f
	gfortran-6 -c -O -fno-align-commons readmol.f
	gfortran-6 -c -O -fno-align-commons readmol2.f
	gfortran-6 -c -O -fno-align-commons readpdb.f
	gfortran-6 -c -O -fno-align-commons readprm.f
	gfortran-6 -c -O -fno-align-commons readseq.f
	gfortran-6 -c -O -fno-align-commons readxyz.f
	gfortran-6 -c -O -fno-align-commons replica.f
	gfortran-6 -c -O -fno-align-commons respa.f
	gfortran-6 -c -O -fno-align-commons rgdstep.f
	gfortran-6 -c -O -fno-align-commons rings.f
	gfortran-6 -c -O -fno-align-commons rmsfit.f
	gfortran-6 -c -O -fno-align-commons rotlist.f
	gfortran-6 -c -O -fno-align-commons rotpole.f
	gfortran-6 -c -O -fno-align-commons saddle.f
	gfortran-6 -c -O -fno-align-commons scan.f
	gfortran-6 -c -O -fno-align-commons sdstep.f
	gfortran-6 -c -O -fno-align-commons search.f
	gfortran-6 -c -O -fno-align-commons server.f
	gfortran-6 -c -O -fno-align-commons shakeup.f
	gfortran-6 -c -O -fno-align-commons sigmoid.f
	gfortran-6 -c -O -fno-align-commons sktstuff.f
	gfortran-6 -c -O -fno-align-commons sniffer.f
	gfortran-6 -c -O -fno-align-commons sort.f
	gfortran-6 -c -O -fno-align-commons spacefill.f
	gfortran-6 -c -O -fno-align-commons spectrum.f
	gfortran-6 -c -O -fno-align-commons square.f
	gfortran-6 -c -O -fno-align-commons suffix.f
	gfortran-6 -c -O -fno-align-commons superpose.f
	gfortran-6 -c -O -fno-align-commons surface.f
	gfortran-6 -c -O -fno-align-commons surfatom.f
	gfortran-6 -c -O -fno-align-commons switch.f
	gfortran-6 -c -O -fno-align-commons sybylxyz.f
	gfortran-6 -c -O -fno-align-commons temper.f
	gfortran-6 -c -O -fno-align-commons testgrad.f
	gfortran-6 -c -O -fno-align-commons testhess.f
	gfortran-6 -c -O -fno-align-commons testpair.f
	gfortran-6 -c -O -fno-align-commons testrot.f
	gfortran-6 -c -O -fno-align-commons timer.f
	gfortran-6 -c -O -fno-align-commons timerot.f
	gfortran-6 -c -O -fno-align-commons tncg.f
	gfortran-6 -c -O -fno-align-commons torphase.f
	gfortran-6 -c -O -fno-align-commons torque.f
	gfortran-6 -c -O -fno-align-commons torsfit.f
	gfortran-6 -c -O -fno-align-commons torsions.f
	gfortran-6 -c -O -fno-align-commons trimtext.f
	gfortran-6 -c -O -fno-align-commons unitcell.f
	gfortran-6 -c -O -fno-align-commons valence.f
	gfortran-6 -c -O -fno-align-commons verlet.f
	gfortran-6 -c -O -fno-align-commons version.f
	gfortran-6 -c -O -fno-align-commons vibbig.f
	gfortran-6 -c -O -fno-align-commons vibrate.f
	gfortran-6 -c -O -fno-align-commons vibrot.f
	gfortran-6 -c -O -fno-align-commons volume.f
	gfortran-6 -c -O -fno-align-commons xtalfit.f
	gfortran-6 -c -O -fno-align-commons xtalmin.f
	gfortran-6 -c -O -fno-align-commons xyzatm.f
	gfortran-6 -c -O -fno-align-commons xyzedit.f
	gfortran-6 -c -O -fno-align-commons xyzint.f
	gfortran-6 -c -O -fno-align-commons xyzpdb.f
	gfortran-6 -c -O -fno-align-commons xyzsybyl.f
	gfortran-6 -c -O -fno-align-commons zatom.f
	gfortran-6 -c -O -fno-align-commons readdiffgrad_qommma.f
